### ISSUE TITLE
Country code ISO 639 - Release new version

### ISSUE THREAD

**Issue by GuilhE** [ParveshSandila/CountryCodeChooser#3]
Is it possible to also get the country code in the [ISO 639 compliant language code](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes)?
Example: `"pt", "+351", "Portugal"`

Working with phone codes is harder than language code, at least I'm not finding a way to having it.

**Comment by GuilhE** [comment]
Curious, I was going to make a PR with this changes and I've noticed that the code in 1.0.1 doesn't have it, but the code in master has it. So a new release is coming (better than using a snapshot)?

ps: created new PR, if accepted, please create a new release to avoid using snapshots (since you publish to jitpack).

**Comment by GuilhE** [comment]
And I've noticed you forgot Mauritania and Venezuela

**Comment by ParveshSandila** [comment]
> Is it possible to also get the country code in the [ISO 639 compliant language code](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes)? Example: `"pt", "+351", "Portugal"`
> 
> Working with phone codes is harder than language code, at least I'm not finding a way to having it.

I was already thinking about that, and in this build, I am definalty going to make this change. Thank you so much for bringing this issue to light.

**Comment by ParveshSandila** [comment]
> 

Sure, I will do that.
